### ISSUE TITLE
I cann't download the splited dataset form the link

### ISSUE THREAD

**Issue by emobuAgent** [ownstyledu/Translate-to-Recognize-Networks#1]

**Comment by ownstyledu** [comment]
Thanks for your attention. Something went wrong with the access permission of our server, and ips outside the school have failed to download the resources now. Since the dataset is public, you could download it yourself, and use our util/splitImages.py to make the data in standard format, and the HHA converter code is also available in [https://github.com/charlesCXK/Depth2HHA-python](url)
